version: "3.8"
services:
  springboot-app:
    build: .
    image: springboot-app
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password